fun main(){
    print("Student Enrollment no.: ")
    val en:String?= readLine()
    print("Student name: ")
    val name:String?=readLine()
    print("Student branch: ")
    val branch:String?=readLine()
    print("Student class: ")
    val cl:String?=readLine()
    print("Student batch: ")
    val batch:String?=readLine()
    print("Student college name: ")
    val cn:String?=readLine()
    print("Student university name: ")
    val un:String?=readLine()
    print("Student age: ")
    val age:String?=readLine()
    print("\n*********************************************\n")
    print("\nStudent data: \n")
    print("Enrollment no: $en\n")
    print("Name: $name\n")
    print("Branch: $branch\n")
    print("Class: $cl\n")
    print("Batch: $batch\n")
    print("College name: $cn\n")
    print("University name: $un\n")
}